"""Shared qualification-scoped Question Bank provider contract."""

from __future__ import annotations
from typing import Protocol

class QuestionBankProvider(Protocol):
    qualification_id: str
    def question_ids(self) -> tuple[str, ...]: ...
    def get_question(self, q_id: str) -> dict: ...
    def get_question_tag(self, q_id: str) -> dict: ...
    def get_quiz_question(self, q_id: str) -> dict: ...
