"""Shared contract for qualification-scoped learner history access."""

from __future__ import annotations
from datetime import datetime
from typing import Protocol

class LearningHistoryStore(Protocol):
    qualification_id: str
    def get_question_attempts(self, user_id: str, start_at: datetime | None = None) -> list[dict]: ...
    def get_question_history(self, user_id: str) -> list[dict]: ...
    def is_initial_assessment_completed(self, user_id: str) -> bool: ...
    def mark_initial_assessment_completed(self, user_id: str) -> None: ...
    def reset_qualification_state(self, user_id: str) -> None: ...
